name: swabeicsdo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  intl: ^0.20.2
  image_picker: ^1.2.0
  logger: ^2.6.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  provider: ^6.1.5+1
  syncfusion_flutter_pdfviewer: ^31.2.2
  syncfusion_flutter_pdf: ^31.2.2
  device_info_plus: ^12.1.0
  sqflite: ^2.3.0
  path_provider: ^2.1.5
  flutter_cache_manager: ^3.4.1
  syncfusion_flutter_xlsio: ^31.2.2
  dio: ^5.9.0
  archive: ^4.0.7
  open_filex: ^4.7.0
  # ✅ Removed manual archive dependency to avoid conflict

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/isabelasdo.png
    - assets/bp.png
    - assets/deped.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" # Path to your image
