const List<String> positions = [
  'Administrative Aide I',
  'Administrative Aide II',
  'Administrative Aide III',
  'Administrative Aide IV',
  'Administrative Aide V',
  'Administrative Aide VI',
  'Administrative Assistant I',
  'Administrative Assistant II',
  'Administrative Assistant III',
  'Administrative Officer I',
  'Administrative Officer II',
  'Administrative Officer III',
  'Administrative Officer IV',
  'Administrative Officer V',
  'Project Development Officer I',
  'Project Development Officer II',
  'Teacher I',
  'Teacher II',
  'Teacher III',
  'Teacher IV',
  'Teacher V',
  'Teacher VI',
  'Teacher VII',
  'Master Teacher I',
  'Master Teacher II',
  'Master Teacher III',
  'Master Teacher IV',
  'Master Teacher V',
  'Principal I',
  'Principal II',
  'Principal III',
  'Principal IV',
  'Engineer III',
  'Senior Education Program Specialist',
  'Education Program Specialist II',
  'Information Technology Officer',
  'Attorney I',
  'Education Program Supervisor',
  'Public Schools District Supervisor',
  'Chief Education Supervisor',
  'Assistant Schools Division Superintendent',
  'Schools Division Superintendent',
];

const List<String> schools = [
  'Isabela East Central Elementary School',
  'Isabela Bliss Elementary School',
  'Bishop Querexeta Elementary School',
  'Kaumpurnah Elementary School',
  'Simeon & Josefa Obsequio Elementary School',
  'Begang Central Elementary School',
  'Busay Elementary School',
  'Tabiawan Elementary School',
  'Latuan Elementary School',
  'Panunsulan Elementary School',
  'Kawa-Kawa Elementary School',
  'Look-Jambangan Elementary School',
  'Kauman Ekka Elementary School',
  'Palasanan Primary School',
  'Spillway Elementary School',
  'Kapatagan Diutay Elementary School',
  'Hadji Camlani Elementary School',
  'Calvario Peak Elementary School',
  'Calvario Elementary School',
  'Masola Elementary School',
  'Lanote Elementary School',
  'Lunot Elementary School',
  'Cabunbata Elementary School',
  'Isabela Central Pilot Elementary School',
  'Ustadz Wahab Akbar Elementary School',
  'Sunset Elementary School',
  'Ajibon Elementary School',
  'Sumagdang Elementary School',
  'Kumalarang Elementary School',
  'Balatanay Elementary School',
  'Balawatin Elementary School',
  'Makiri Elementary School',
  'Campo Barn Elementary School',
  'Hadji Maulana Primary School',
  'Caro Elementary School',
  'Malamawi Central Elementary School',
  'Tampalan Elementary School',
  'Diki Elementary School',
  'Marang Marang Elementary School',
  'Lukbuton Elementary School',
  'Hadji Amilhamja Lahaba Memorial Elementary School',
  'MS Bernardo Elementary School',
  'Lampinigan Elementary School',
  'Basilan National High School',
  'Baluno National High School',
  'Malamawi National High School',
  'Begang National High School',
  'Isabela City National High School',
  'Kumalarang National High School',
  'Ismael Integrated School',
  'Panigayan Integrated School',
  'Badjao Floating Integrated School',
  'Geras Integrated School',
  'Lampinigan National High School',
  'Tandung Ahas National High School',
];
