// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-X_FMqpYHuwtwunTNPzzd3HFdYXEc2Xo',
    appId: '1:552137708069:web:a5c493df90c881bfc3a5cc',
    messagingSenderId: '552137708069',
    projectId: 'swabeicsdo-9014f',
    authDomain: 'swabeicsdo-9014f.firebaseapp.com',
    storageBucket: 'swabeicsdo-9014f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDojU3-9ZIvzFaP6Q3syR4ZEsMcxfNImok',
    appId: '1:552137708069:android:e5f50b59edc6189cc3a5cc',
    messagingSenderId: '552137708069',
    projectId: 'swabeicsdo-9014f',
    storageBucket: 'swabeicsdo-9014f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7SrpgS9LmiexTYhoPlb9a3Ja1e6m8Qpw',
    appId: '1:552137708069:ios:a78823fbd2c275bdc3a5cc',
    messagingSenderId: '552137708069',
    projectId: 'swabeicsdo-9014f',
    storageBucket: 'swabeicsdo-9014f.firebasestorage.app',
    iosBundleId: 'com.example.swabeicsdo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7SrpgS9LmiexTYhoPlb9a3Ja1e6m8Qpw',
    appId: '1:552137708069:ios:a78823fbd2c275bdc3a5cc',
    messagingSenderId: '552137708069',
    projectId: 'swabeicsdo-9014f',
    storageBucket: 'swabeicsdo-9014f.firebasestorage.app',
    iosBundleId: 'com.example.swabeicsdo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-X_FMqpYHuwtwunTNPzzd3HFdYXEc2Xo',
    appId: '1:552137708069:web:7ce6696b4f3db52fc3a5cc',
    messagingSenderId: '552137708069',
    projectId: 'swabeicsdo-9014f',
    authDomain: 'swabeicsdo-9014f.firebaseapp.com',
    storageBucket: 'swabeicsdo-9014f.firebasestorage.app',
  );

}